server {
    listen 9100;
    server_name localhost;

    # Location of expo exported files
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # If a route is not found, fall back to index.html for single page application routing
        try_files $uri $uri/ /index.html;
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
